spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkat4-sys/ConfigurationProperties.git
          clone-on-start: true
  application:
     name: CONFIG-SERVER   
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka        